import Head from "next/head";
import dynamic from "next/dynamic";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import HomePage from "../components/HomePage";
import Login from "./login";
import FindAJob from "./find-a-job";


export default function Home() {
  return (
    <>
      <Head>
        <title>MPR Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <HomePage />
        <Footer />
      </>
    </>
  );
}
